<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SUSESS.aspx.cs" Inherits="WebApplication1.SUSESS" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1 style="text-align:center;font-family:標楷體">
                <asp:Label ID="Label1" runat="server" Text="成功登入!!!"></asp:Label></h1>
             <p>&nbsp;&nbsp; </p>
              <p>&nbsp;&nbsp; </p>
              <p>&nbsp;&nbsp; </p>
            <p style="text-align:center"><asp:FileUpload ID="FileUpload1" runat="server" /> </p>
             <p style="text-align:center"> <asp:Button ID="Button1" runat="server" Text="顯示EXCEL資料" BackColor="Black" Font-Bold="True" ForeColor="Red" Height="47px" OnClick="Button1_Click" Width="133px" /> 
                 &nbsp;&nbsp; 
                 <asp:Button ID="Button3" runat="server" Text="匯出EXCEL檔案" BackColor="Black" Font-Bold="True" ForeColor="Red" Height="47px" OnClick="Button3_Click" Width="133px" />
             </p>
            
             <H3 style="text-align:center">
                 <asp:Label ID="Label2" runat="server" Text="姓名：" Visible="False"></asp:Label><asp:TextBox ID="TextBox_name" runat="server" Width="41px" Visible="False" AutoPostBack="True" OnTextChanged="TextBox_name_TextChanged"></asp:TextBox> 
                 <asp:Label ID="Label3" runat="server" Text="段考一：" Visible="False"></asp:Label><asp:TextBox ID="TextBox_test1" runat="server" Width="41px" Visible="False"></asp:TextBox>
                 <asp:Label ID="Label4" runat="server" Text="段考二：" Visible="False"></asp:Label><asp:TextBox ID="TextBox_test2" runat="server" Width="41px" Visible="False"></asp:TextBox>
                 <asp:Label ID="Label5" runat="server" Text="段考三：" Visible="False"></asp:Label><asp:TextBox ID="TextBox_test3" runat="server" Width="41px" Visible="False"></asp:TextBox>
                 <asp:Label ID="Label6" runat="server" Text="小考：" Visible="False"></asp:Label><asp:TextBox ID="TextBox_exam" runat="server" Width="41px" Visible="False"></asp:TextBox>
                 <asp:Label ID="Label7" runat="server" Text="分數：" Visible="False"></asp:Label><asp:TextBox ID="TextBox_grade" runat="server" Width="41px" Visible="False"></asp:TextBox>
             &nbsp;
                 <asp:Button ID="Button2" runat="server" Text="新增資料" Visible="False" OnClick="Button2_Click" Width="75px"/>
             </H3>
            
            <div style="width:80%;float:right;"><asp:GridView ID="GridView1" runat="server" AllowPaging="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnPageIndexChanging="GridView1_PageIndexChanging" Visible="False" Width="622px" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDeleting="GridView1_RowDeleting">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                </Columns>
                <EditRowStyle BackColor="#7C6F57" />
                <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#E3EAEB" />
                <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F8FAFA" />
                <SortedAscendingHeaderStyle BackColor="#246B61" />
                <SortedDescendingCellStyle BackColor="#D4DFE1" />
                <SortedDescendingHeaderStyle BackColor="#15524A" />
                 </asp:GridView> </div>
         
        </div>
        

    </form>
</body>
</html>
